# -*- coding: utf-8 -*-
"""Sentiment+Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G8bWAat6hjinh5NWCOmJ8iLjl_9F0W-5
"""

import pandas as pd
import numpy as np
import pickle

df = pd.read_csv('Amazon_Unlocked_Mobile.csv', engine='python')

df.head()

df.dropna(inplace=True)

df = df[df['Rating'] != 3]

# Encode 4s and 5s as 1 (rated positively)
# Encode 1s and 2s as 0 (rated poorly)

df['Positively Rated'] = np.where(df['Rating'] > 3, 1, 0)
df.head(10)

df['Positively Rated'].mean()

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['Reviews'], 
                                                    df['Positively Rated'], 
                                                    random_state=0)

"""# CountVectorizer"""

from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer().fit(X_train)

vect.get_feature_names()[::2000]

len(vect.get_feature_names())

X_train_vectorized = vect.transform(X_train)

X_train_vectorized

from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_train_vectorized, y_train)

pickle.dump(log_reg, open('model.pkl', 'wb'))
model = pickle.load(open('model.pkl', 'rb'))

pickle.dump(vect, open("vector.pkl", "wb"))

#